main_node:
  hosts:
    node1:
      ansible_host: 20.163.117.231
      ansible_ssh_private_key_file: ~/.ssh/machinekey.pem
      ansible_ssh_user: ubuntu
# ssh -i ~/.ssh/id_rsa remote_machine_username@Node_IP
